package br.com.bragasaude.ai

/** Catálogo operacional com frases delimitadas e telas verificadas; só fornece orientação. */
internal object BragaAppHelp {
    private data class Guide(val intent: String, val pattern: Regex, val reply: String)
    private fun guide(intent: String, pattern: String, reply: String) = Guide("ajuda_$intent", Regex("^(?:$pattern)$"), reply)
    private val guides = listOf(
        guide("tutorial_app", "como (?:vejo|rever|revejo|abro) (?:o )?tutorial(?: de novo)?|onde (?:fica|vejo) (?:o )?tutorial", "Em Configurações, toque em Ver Tutorial do Aplicativo para rever o tour guiado."),
        guide("feedback_app", "como (?:falo com|contato) (?:os )?desenvolvedores|como envio (?:uma )?(?:sugestao|feedback)|onde envio (?:uma )?sugestao", "Em Configurações, toque em Falar com os Desenvolvedores. Você pode enviar sugestões ou observações por texto ou voz."),
        guide("excluir_conta", "como (?:excluo|excluir|apago|apagar) (?:a )?(?:minha )?(?:conta|perfil)|onde excluo (?:minha )?conta", "Em Configurações, use Excluir Perfil e Conta. Leia a confirmação antes de Excluir Definitivamente: a exclusão é permanente. Esta conversa não exclui sua conta."),
        guide("notificacoes_app", "como (?:ativo|ativar|habilito|habilitar) (?:as )?notificacoes(?: de saude)?|onde (?:ativo|habilito) (?:as )?notificacoes", "Em Configurações, confira Notificações de Saúde. Confira também se o Android permite notificações do Braga Saúde nas configurações do aplicativo."),
        guide("lembrete_sem_aviso", "(?:por que|porque) (?:meu |o )?lembrete nao (?:tocou|avisou)|(?:meu |o )?lembrete nao tocou", "Confira o horário cadastrado, Notificações de Saúde em Configurações e a permissão de notificações do Braga Saúde no Android. Confira também restrições de bateria. A mensagem, sozinha, não permite identificar a causa do aviso ausente."),
        guide("registrar_dose_app", "como (?:registro|registrar|anoto|anotar) (?:que )?(?:eu )?tomei (?:meu |o )?(?:remedio|medicamento)|como registro (?:uma |a )?dose", "Em Lembretes, confira o medicamento e use Registrar dose. Confira o medicamento, horário e quantidade antes de confirmar. Esta orientação não registra uma dose nem muda sua receita."),
        guide("desfazer_agua", "como (?:desfaco|desfazer|removo|remover) (?:a )?agua (?:que )?(?:eu )?registrei(?: agora)?", "Na tela de hidratação, Desfazer remove o último registro de água. Confira se é o registro que deseja remover. Esta conversa não removeu dados."),
        guide("formatos_exame", "posso (?:enviar|anexar) (?:uma )?foto ou pdf(?: do exame)?|como envio (?:uma )?(?:foto|pdf)(?: de (?:um )?exame)?", "Abra Organizar exames, selecione PDFs ou fotos e confira todas as páginas, título, data e tipo. Gere o PDF com índice e salve fora do aplicativo. Esta área é temporária: as cópias expiram em 24 horas. Não há biblioteca nem envio ao servidor. Esta conversa não importa documentos por você."),
        guide("revisar_exame", "(?:o )?valor (?:lido|transcrito) (?:da foto|do exame) esta errado(?:,)? como (?:corrijo|corrigir)|como (?:corrijo|edito) (?:o )?(?:valor|resultado) (?:da foto|do exame)", "Na revisão, confira o documento original e edite valor e unidade antes de salvar. Para um exame salvo, abra seus detalhes e use Conferir ou editar resultados. Não alterei os resultados por esta conversa."),
        guide("armazenamento_exame", "(?:meus |os )?exames (?:estao|ficam) (?:so |somente )?(?:neste celular|no aparelho)|onde (?:meus |os )?exames ficam salvos", "Abra Organizar exames, selecione PDFs ou fotos e confira todas as páginas, título, data e tipo. Gere o PDF com índice e salve fora do aplicativo. Esta área é temporária: as cópias expiram em 24 horas. Não há biblioteca nem envio ao servidor. Esta conversa não importa documentos por você."),
        guide("remover_nuvem_exame", "como (?:retiro|removo|remover|apago) (?:a )?copia (?:do exame )?da nuvem|como (?:retiro|removo) (?:o )?exame da nuvem", "Abra os detalhes do exame e confira Remover cópia da nuvem e manter no aparelho. Leia a confirmação e confira se a cópia local está disponível. Parar novos envios à nuvem é outra opção e não equivale a remover uma cópia existente. Esta conversa não removeu arquivos."),
        guide("compartilhar_relatorio", "como (?:mando|envio|compartilho) (?:o |meu )?relatorio (?:para|com) (?:o |meu )?medico", "Em Dados e Relatórios, gere o PDF dos últimos 30 dias. Abra o arquivo num leitor de PDF e use a opção de compartilhar, se disponível. Confira o destinatário. Esta conversa não envia o relatório."),
        guide("historico_indireto", "pode me mostrar onde (?:fica|esta) (?:o |meu )?historico", "Você pode pedir a última pressão, a glicemia de ontem ou a água registrada hoje. Para o PDF, abra Dados e Relatórios e toque em Baixar Relatório em PDF."),
        guide("uso_sem_internet", "(?:consigo|posso) usar (?:o app |o aplicativo )?sem internet|(?:o app |o aplicativo )?funciona (?:offline|sem internet)", "O NLU e as consultas a registros já salvos neste aparelho funcionam localmente. Inferência externa, envio à nuvem e comunicação entre contas dependem de conexão. Ter dados locais não garante que estejam sincronizados em outro aparelho."),
        guide("conectar_familiar", "como (?:conecto|conectar|adiciono|adicionar) (?:meu |um |o )?(?:cuidador|familiar)", "No Círculo Familiar, use o código de conexão e confira quem está sendo vinculado. Compartilhe o código apenas com a pessoa escolhida e confira as permissões do vínculo. Esta orientação não conecta ninguém."),
        guide("revogar_familiar", "como (?:retiro|removo|revogo) (?:o )?acesso (?:de (?:um |meu )?familiar|do (?:meu )?cuidador)", "No Círculo Familiar, confira a pessoa vinculada e use Remover acesso. Leia a confirmação antes de concluir. Esta conversa não revogou o vínculo."),
        guide("dados_familiar", "(?:meu |o )?cuidador (?:consegue|pode) ver quais dados|quais dados (?:meu |o )?cuidador (?:ve|pode ver)", "O acesso depende do vínculo e das permissões de compartilhamento. Confira a pessoa e os consentimentos no Círculo Familiar. Não presuma que compartilhar um PDF ativa acompanhamento automático nem que todos os exames estejam compartilhados."),
        guide("recado_familiar", "como (?:mando|envio) (?:um )?recado (?:para|pra) (?:minha mae|meu pai|meu familiar)", "Use a conversa da pessoa vinculada na área familiar e confira o destinatário antes de enviar. Esta orientação não envia um recado por você."),
        guide("compras_app", "como (?:adiciono|adicionar|coloco) (?:um )?alimento (?:a|na) lista de compras", "Na área de alimentação, abra a lista de compras e adicione o alimento pela tela. Confira o item e a quantidade. Esta conversa não alterou a lista."),
        guide("receitas_lista", "onde (?:vejo|encontro) (?:as )?receitas (?:da|de) (?:minha )?lista", "Na área de alimentação, abra Receitas da Minha Lista. Confira os ingredientes e as restrições cadastradas antes de usar uma receita."),
        guide("alergia_perfil", "como (?:informo|cadastro|cadastrar|adiciono) (?:uma |minha )?alergia alimentar", "No perfil, confira Alergias & Restrições Alimentares e salve as informações corretas. A conversa não alterou seu cadastro. Confira os ingredientes das receitas mesmo após cadastrar restrições."),
        guide("conectar_relogio", "como (?:conecto|conectar|sincronizo) (?:meu |o )?relogio", "Abra Relógios e saúde. Pareie o relógio no aplicativo do fabricante, habilite o compartilhamento com Health Connect e autorize o Braga Saúde. Funciona com fabricantes que compartilham esses dados; autorizar não garante que já existam leituras."),
        guide("passos_sem_atualizacao", "(?:por que|porque) (?:meus |os )?passos nao (?:atualizaram|atualizam|aparecem)", "Confira Localização e Passos em Configurações e as permissões do Android. Se a fonte é um relógio, confira o compartilhamento do fabricante com Health Connect e sincronize em Relógios e saúde. Não consigo identificar a causa só pela mensagem."),
        guide("meta_passos", "como (?:altero|alterar|mudo|mudar|edito) (?:a |minha |a minha )?meta (?:diaria )?de passos", "Em Configurações, toque em Meta Diária de Passos, ajuste o valor e confira antes de salvar. Esta conversa não alterou a meta."),
        guide("voz_assistente", "como (?:mudo|mudar|altero|alterar|troco) (?:a )?voz (?:do braga|do assistente)", "Em Configurações, toque em Voz do assistente e escolha entre as opções disponíveis. Confira a voz selecionada; algumas opções podem precisar ser preparadas antes de usar."),
        guide("contexto_glicemia", "qual (?:a |e a )?diferenca entre glicemia em jejum e (?:depois de comer|apos (?:a )?refeicao)", "No app, jejum e após refeição são contextos diferentes da medição. O tipo anotado acompanha o valor e pode ser usado para filtrar a consulta. Confira o contexto correto ao registrar; não trato tipos diferentes como medições equivalentes."),
        guide("bebida_agua_app", "cha conta como agua", "O total de água no app descreve os registros de água. Uma mensagem sobre chá não deve virar automaticamente um registro de água. Para orientações individuais sobre bebidas ou restrição de líquidos, siga o profissional que acompanha você.")
    )

    fun supports(intent: String) = guides.any { it.intent == intent }

    fun answer(input: String): NluOutput? = guides.firstOrNull { it.pattern.matches(input) }?.let { NluOutput(it.intent, it.reply) }
}
